exports.people = [
	"Birgit Morlion",
	"Diederik Decroix",
	"Dominique Moens",
	"Elise Descamps",
	"Els Van Bruystegem",
	"Emilie Vandemeulebroeke",
	"Jan Coppens",
	"Kasper Jordaens",
	"Katia De Busschere",
	"Kenny Garré",
	"Koen De Vos",
	"Lesley Neels",
	"Liesbeth Van der Haegen",
	"Lisa Pattyn",
	"Lode Nachtergaele",
	"Marleen Heyndrickx",
	"Marlies Criel",
	"Martijn Bal",
	"Matthias De Geyter",
	"Melissa Beelaert",
	"Nele Rubrecht",
	"Olivier Rosseel",
	"Sam Decrock",
	"Sofie Verhoeve",
	"Stefan Vermeulen",
	"Steven Van Assche",
	"Sven De Cleyn",
	"Ana Santos",
	"Karen Boers",
	"Kenny Willems",
	"Lies Boghaert",
	"Loy Van Hamme",
	"Nico Verplancke",
	"Raf De Kimpe",
	"Thomas Kallstenius",
	"Veronique Elegheert",
	"Wim De Waele",
	"Carina Veeckman",
	"Caroline Luneaut",
	"Delphine Dewilde",
	"Helga Deschrijver",
	"Katrien Van Gucht",
	"Katrien Wemel",
	"Koen Vervoort",
	"Koen Vriesacker",
	"Matthias Priem",
	"Sabine Castelein",
	"Danny Goderis",
	"Frank Gielen",
	"Ilse Roelants",
	"Janick De Witte",
	"Jenny Van Overwaele",
	"Koen Hendrickx",
	"Sabine De Moor",
	"Stefan Van Baelen",
	"Wendy Ruys",
	"Wendy Van Bockhaven"];

